name: 00-Init-Repository-Pet-Clinic

on:
  workflow_dispatch:

permissions:
    contents: write
    packages: write
    id-token: write
      
jobs:
    pets-config-svc:
        uses: ./.github/workflows/72-continuous-integration-pets-config-srv.yml
        secrets: inherit
    pets-admin-svc:
        needs: pets-config-svc
        uses: ./.github/workflows/73-continuous-integration-pets-admin-srv.yml
        secrets: inherit
    pets-disco-svc:
        needs: pets-admin-svc
        uses: ./.github/workflows/74-continuous-integration-pets-disco-svc.yml
        secrets: inherit
    pets-utils-01-zipkin:
        needs: pets-disco-svc
        uses: ./.github/workflows/79-continuous-integration-utils-01-zipkin.yml
        secrets: inherit
    pets-utils-02-prometheus:
        needs: pets-disco-svc
        uses: ./.github/workflows/79-continuous-integration-utils-02-prometheus.yml
        secrets: inherit
    pets-utils-03-grafana:
        needs: pets-disco-svc
        uses: ./.github/workflows/79-continuous-integration-utils-03-grafana.yml
        secrets: inherit
    pets-custs-svc:
        needs: [pets-utils-01-zipkin, pets-utils-02-prometheus, pets-utils-03-grafana]
        uses: ./.github/workflows/76-continuous-integration-pets-custs-svc.yml
        secrets: inherit
    pets-vets-svc:
        needs: [pets-utils-01-zipkin, pets-utils-02-prometheus, pets-utils-03-grafana]
        uses: ./.github/workflows/77-continuous-integration-pets-vets-svc.yml
        secrets: inherit
    pets-visits-svc:
        needs: [pets-utils-01-zipkin, pets-utils-02-prometheus, pets-utils-03-grafana]
        uses: ./.github/workflows/78-continuous-integration-pets-visits-svc.yml
        secrets: inherit
    pets-api-gw:
        needs: [pets-custs-svc, pets-vets-svc, pets-visits-svc]
        uses: ./.github/workflows/75-continuous-integration-pets-api-gw.yml
        secrets: inherit
