name: 91-Continuous-Delivery-Todo-App

on:
  # release: - causes problem with az login with a federated identity - asterisk not supported
  #   types: [released]
  workflow_call:
    inputs:
      version:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: Full version tag (e.g. "v1.0.5")

permissions:
  id-token: write
  contents: read
  packages: read

jobs:
  deploy:
    env:
      ARTIFACT_NAME: todo-app
      APP_NAME: todo-app
      SRC_DIR: todo-app
      JAVA_VERSION: 11
      USER_IDENTITY_NAME: ${{secrets.ACA_NAME}}-todo-app-identity
      PGSQL_NAME: ${{secrets.PGSQL_NAME}}
      DB: ${{secrets.TODO_APP_DB_NAME}}
      DB_USER_NAME: ${{secrets.TODO_APP_DB_USER_NAME}}
      DBA_GROUP_NAME: ${{secrets.DBA_GROUP_NAME}}
      CONTAINER_REGISTRY_SUBSCRIPTION_ID: ${{secrets.CONTAINER_REGISTRY_SUBSCRIPTION_ID  || secrets.ACA_SUBSCRIPTION_ID}}
      CONTAINER_REGISTRY_NAME: ${{secrets.CONTAINER_REGISTRY_NAME}}
      CONTAINER_REGISTRY_RESOURCE_GROUP: ${{secrets.CONTAINER_REGISTRY_RESOURCE_GROUP || secrets.ACA_RESOURCE_GROUP}}
      ACA_RESOURCE_GROUP: ${{secrets.ACA_RESOURCE_GROUP}}
      ACA_NAME: ${{secrets.ACA_NAME}}
      ACA_SUBSCRIPTION_ID: ${{secrets.ACA_SUBSCRIPTION_ID}}

    # when called from another workflow directly, it inherits the event name from the caller workflow
    # (push in this case when called from 10-continuous-integration.yml)
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/v') || ((github.event_name == 'workflow_dispatch' || github.event_name == 'workflow_call' || (github.event_name == 'push' && github.ref == 'refs/heads/main')) && startsWith(inputs.version,'v')) }} 
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Init version numbers
        id: versions
        run: |
          releaseVersion=""
          if [[ "${{github.event_name}}" == "workflow_dispatch" ]]; then
            releaseVersion="${{inputs.version}}" 
          elif [[ "${{github.event_name}}" == "workflow_call" ]]; then
            releaseVersion="${{inputs.version}}" 
          elif [[ "${{github.event_name}}" == "release" ]]; then
            releaseVersion="${{github.event.release.tag_name}}" 
          elif [[ "${{github.event_name}}" == "push" ]]; then
            releaseVersion="${{inputs.version}}" 
          else
            echo "Unknown trigger: '${{github.event_name}}'"
            exit 1
          fi
          echo "Release version to deploy: ${releaseVersion}"

          if [[ ${releaseVersion::1} == "v" ]]; then
            releaseVersionNumber="${releaseVersion:1}"
          else
            releaseVersionNumber="${releaseVersion}"
          fi

          echo "Release version number to deploy: ${releaseVersionNumber}"
          echo "VERSION=${releaseVersionNumber}" >> $GITHUB_OUTPUT
          echo "VERSION_TAG=v${releaseVersionNumber}-${{env.ARTIFACT_NAME}}" >> $GITHUB_OUTPUT
          echo "RELEASE_DIR_NAME=${{env.ARTIFACT_NAME}}-${releaseVersionNumber}" >> $GITHUB_OUTPUT
          echo "RELEASE_ARCHIVE_NAME=${{env.ARTIFACT_NAME}}-${releaseVersionNumber}.zip" >> $GITHUB_OUTPUT
          echo "RELEASE_FILE_NAME=${{env.ARTIFACT_NAME}}-${releaseVersionNumber}.jar" >> $GITHUB_OUTPUT

      - name: Download release
        id: download_release
        continue-on-error: true
        env:
          GH_TOKEN: ${{ github.token }}
          VERSION_TAG: ${{steps.versions.outputs.VERSION_TAG}}
          RELEASE_ARCHIVE_NAME: ${{steps.versions.outputs.RELEASE_ARCHIVE_NAME}}
        run: |
            echo "RELEASE_EXISTS=false" >> $GITHUB_OUTPUT
            gh release download ${{env.VERSION_TAG}} -D ./
            echo "Unzipping the release archive file: ${{env.RELEASE_ARCHIVE_NAME}}"
            unzip ${{env.RELEASE_ARCHIVE_NAME}}
            echo "RELEASE_EXISTS=true" >> $GITHUB_OUTPUT

      - name: Display parameters
        id: params
        run: |
          echo "ARTIFACT_NAME=${{env.ARTIFACT_NAME}}"
          echo "VERSION=${{steps.versions.outputs.VERSION}}"
          echo "VERSION_TAG=${{steps.versions.outputs.VERSION_TAG}}"
          echo "RELEASE_EXISTS=${{steps.download_release.outputs.RELEASE_EXISTS}}"
          echo "RELEASE_ARCHIVE_NAME=${{steps.versions.outputs.RELEASE_ARCHIVE_NAME}}"
          echo "RELEASE_DIR_NAME=${{steps.versions.outputs.RELEASE_DIR_NAME}}"
          echo "RELEASE_FILE_NAME=${{steps.versions.outputs.RELEASE_FILE_NAME}}"
          echo "JAVA_VERSION=${{env.JAVA_VERSION}}"
          echo "DB=${{env.DB}}"

          echo "GITHUB_SHA=${{github.sha}}"
          echo "GITHUB_REF=${{github.ref}}"
          echo "GITHUB_EVENT_NAME=${{github.event_name}}"

          echo "DB_NAME=${{env.DB}}" >> "$GITHUB_OUTPUT"
          echo "DB_NAME: ${{env.DB}}"
          
      - name: Fail if release does not exist
        if: ${{ steps.download_release.outputs.RELEASE_EXISTS == 'false' }}
        env:
          VERSION: ${{steps.versions.outputs.VERSION}}
        run: |
            echo "Release '${{env.VERSION}}' does not exist."
            exit 1

      - name: Azure login in ACA Subscription # https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure
        uses: azure/login@v2
        with:
          client-id: "${{secrets.AAD_CLIENT_ID}}"
          tenant-id: "${{secrets.AAD_TENANT_ID}}"
          subscription-id: "${{env.CONTAINER_REGISTRY_SUBSCRIPTION_ID}}"

      - name: Check container exists in registry
        id: check_container_exists
        continue-on-error: true
        env:
          VERSION: ${{steps.versions.outputs.VERSION}}
        run: |
          echo "CONTAINER_EXISTS=false" >> $GITHUB_OUTPUT
          az acr repository show --name ${{env.CONTAINER_REGISTRY_NAME}} --image "${{env.ARTIFACT_NAME}}:${{env.VERSION}}" --subscription "${{env.CONTAINER_REGISTRY_SUBSCRIPTION_ID}}"
          echo "CONTAINER_EXISTS=true" >> $GITHUB_OUTPUT

      - name: Publish container if it does not exist
        if: ${{ steps.check_container_exists.outputs.CONTAINER_EXISTS == 'false' }}
        env:
          GH_TOKEN: ${{ github.token }}
          VERSION: ${{steps.versions.outputs.VERSION}}
          RELEASE_ARCHIVE_NAME: ${{steps.versions.outputs.RELEASE_ARCHIVE_NAME}}
          RELEASE_DIR_NAME: ${{steps.versions.outputs.RELEASE_DIR_NAME}}
          RELEASE_FILE_NAME: ${{steps.versions.outputs.RELEASE_FILE_NAME}}
        run: |
          ls -la
          if [[ ! -f "${{env.RELEASE_DIR_NAME}}/${{env.RELEASE_FILE_NAME}}" ]]; then
            echo "'${{env.RELEASE_DIR_NAME}}/${{env.RELEASE_FILE_NAME}}' does not exist."
            exit 1
          fi
          
          cd ./${{env.RELEASE_DIR_NAME}}
          mv ./Dockerfile ./Dockerfile.tmp
          # Dockerfile syntax is driving me bonkers. This should work...
          cat ./Dockerfile.tmp | ARTIFACT_NAME_ARG=${{env.ARTIFACT_NAME}} VERSION_ARG=${{env.VERSION}} envsubst > ./Dockerfile
          cat ./Dockerfile
  
          az acr build ./ -r ${{env.CONTAINER_REGISTRY_NAME}} -t "${{env.ARTIFACT_NAME}}:${{env.VERSION}}" --file ./Dockerfile --subscription "${{env.CONTAINER_REGISTRY_SUBSCRIPTION_ID}}"
          cd ..

      - name: Synchronize DB Schema
        if: ${{ env.DB != '' }}
        env:
          PGSQL_SERVER_NAME: '${{env.PGSQL_NAME}}.postgres.database.azure.com'
          PGSQL_SERVER_NAME_SHORT: '${{env.PGSQL_NAME}}'
        run: |
          # Figure which service user to use and it's appId .. never know when to use id and when to use appId.
          appClientId=`az ad sp list --display-name "${{env.USER_IDENTITY_NAME}}" --query "[?displayName=='${{env.USER_IDENTITY_NAME}}'].appId" --out tsv`
        
          echo "DB user: ${{env.DB_USER_NAME}}"
          echo "Managed identity name: ${{env.USER_IDENTITY_NAME}}"
          echo "Managed identity appClientId: ${appClientId}"
            
          # Retrieve PGSQL access token 
          export PGPASSWORD=`az account get-access-token --resource-type oss-rdbms --query "[accessToken]" --output tsv`
          echo "Token: ${PGPASSWORD}"
          
          # Create a new service user if needed - trying without -p <password> 
          dbUserExists=`az postgres flexible-server execute -n "${{env.PGSQL_SERVER_NAME_SHORT}}" -u "${{env.DBA_GROUP_NAME}}" -p "${PGPASSWORD}" -d "${{env.DB}}" -q "SELECT 1 FROM pg_roles WHERE rolname='${{env.DB_USER_NAME}}';" --allow-preview true -o tsv`
          # dbUserExists=`psql --set=sslmode=require -h ${{env.PGSQL_SERVER_NAME}} -p 5432 -d "${{env.DB}}" -U "${{env.DBA_GROUP_NAME}}" -tAc "SELECT 1 FROM pg_roles WHERE rolname='${{env.DB_USER_NAME}}';" -v ON_ERROR_STOP=1`
          if [[ $dbUserExists -ne '1' ]]; then
            echo "User '${{env.DB_USER_NAME}}' does not exist yet, creating the user"
            # psql --set=sslmode=require -h ${{env.PGSQL_SERVER_NAME}} -p 5432 -d "${{env.DB}}" -U "${{env.DBA_GROUP_NAME}}" -tAc "CREATE ROLE ${{env.DB_USER_NAME}} LOGIN;" -v ON_ERROR_STOP=1
            az postgres flexible-server execute -n "${{env.PGSQL_SERVER_NAME_SHORT}}" -u "${{env.DBA_GROUP_NAME}}" -p "${PGPASSWORD}" -d "${{env.DB}}" -q "CREATE ROLE ${{env.DB_USER_NAME}} LOGIN;" --allow-preview true 
          else
            echo "User '${{env.DB_USER_NAME}}' already exists, skipping the creation"
          fi
          # psql --set=sslmode=require -h ${{env.PGSQL_SERVER_NAME}} -p 5432 -d "${{env.DB}}" -U "${{env.DBA_GROUP_NAME}}" -tAc "security label for pgaadauth on role ${{env.DB_USER_NAME}} is 'aadauth,oid=${appClientId},type=service';" -v ON_ERROR_STOP=1
          az postgres flexible-server execute -n "${{env.PGSQL_SERVER_NAME_SHORT}}" -u "${{env.DBA_GROUP_NAME}}" -p "${PGPASSWORD}" -d "${{env.DB}}" -q "security label for pgaadauth on role ${{env.DB_USER_NAME}} is 'aadauth,oid=${appClientId},type=service';" --allow-preview true 
            
          # Sync DB Schema
          # psql --set=sslmode=require -h "${{env.PGSQL_SERVER_NAME}}" -p 5432 -d "${{env.DB}}" -U "${{env.DBA_GROUP_NAME}}" --file=./${{env.ARTIFACT_NAME}}-${{steps.versions.outputs.VERSION}}/db/pgsql/schema.sql -v ON_ERROR_STOP=1
          az postgres flexible-server execute -n "${{env.PGSQL_SERVER_NAME_SHORT}}" -u "${{env.DBA_GROUP_NAME}}" -p "${PGPASSWORD}" -d "${{env.DB}}" --file-path=./${{env.ARTIFACT_NAME}}-${{steps.versions.outputs.VERSION}}/db/pgsql/schema.sql --allow-preview true

          # Load (demo) data
          # psql --set=sslmode=require -h "${{env.PGSQL_SERVER_NAME}}" -p 5432 -d "${{env.DB}}" -U "${{env.DBA_GROUP_NAME}}" --file=./${{env.ARTIFACT_NAME}}-${{steps.versions.outputs.VERSION}}/db/pgsql/data.sql -v ON_ERROR_STOP=1
          az postgres flexible-server execute -n "${{env.PGSQL_SERVER_NAME_SHORT}}" -u "${{env.DBA_GROUP_NAME}}" -p "${PGPASSWORD}" -d "${{env.DB}}" --file-path=./${{env.ARTIFACT_NAME}}-${{steps.versions.outputs.VERSION}}/db/pgsql/data.sql --allow-preview true
            
          # Grant the newly create service user all necessary rights
          # psql --set=sslmode=require -h "${{env.PGSQL_SERVER_NAME}}" -p 5432 -d "${{env.DB}}" -U "${{env.DBA_GROUP_NAME}}" -tAc "GRANT CONNECT ON DATABASE ${{env.DB}} TO ${{env.DB_USER_NAME}};" -v ON_ERROR_STOP=1
          # psql --set=sslmode=require -h "${{env.PGSQL_SERVER_NAME}}" -p 5432 -d "${{env.DB}}" -U "${{env.DBA_GROUP_NAME}}" -tAc "GRANT USAGE ON SCHEMA public TO ${{env.DB_USER_NAME}};" -v ON_ERROR_STOP=1
          # psql --set=sslmode=require -h "${{env.PGSQL_SERVER_NAME}}" -p 5432 -d "${{env.DB}}" -U "${{env.DBA_GROUP_NAME}}" -tAc "GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ${{env.DB_USER_NAME}};" -v ON_ERROR_STOP=1
          az postgres flexible-server execute -n "${{env.PGSQL_SERVER_NAME_SHORT}}" -u "${{env.DBA_GROUP_NAME}}" -p "${PGPASSWORD}" -d "${{env.DB}}" -q "GRANT CONNECT ON DATABASE ${{env.DB}} TO ${{env.DB_USER_NAME}};" --allow-preview true
          az postgres flexible-server execute -n "${{env.PGSQL_SERVER_NAME_SHORT}}" -u "${{env.DBA_GROUP_NAME}}" -p "${PGPASSWORD}" -d "${{env.DB}}" -q "GRANT USAGE ON SCHEMA public TO ${{env.DB_USER_NAME}};" --allow-preview true
          az postgres flexible-server execute -n "${{env.PGSQL_SERVER_NAME_SHORT}}" -u "${{env.DBA_GROUP_NAME}}" -p "${PGPASSWORD}" -d "${{env.DB}}" -q "GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ${{env.DB_USER_NAME}};" --allow-preview true

      - name: Deploy app into ACA using Bicep
        env:
          DEPLOYMENT_SUFFIX: ""
          CONTAINER_IMAGE: ${{env.CONTAINER_REGISTRY_NAME}}.azurecr.io/${{env.ARTIFACT_NAME}}:${{steps.versions.outputs.VERSION}}
          RELEASE_DIR_NAME: ${{steps.versions.outputs.RELEASE_DIR_NAME}}
          HOST_NAME: ${{env.APP_NAME}}.${{secrets.DNS_ZONE_NAME}}.${{secrets.PARENT_DNS_ZONE_NAME}}
          VERSION: ${{steps.versions.outputs.VERSION}}
        run: |
          ls ./${{env.RELEASE_DIR_NAME}}/aca/
          certificateId=''
          if [[ ! -z ${{secrets.DNS_ZONE_NAME}} ]]; then
            certificateId=`az containerapp env certificate list -g ${{env.ACA_RESOURCE_GROUP}} --name ${{env.ACA_NAME}} --query "[?properties.subjectName=='${{env.HOST_NAME}}'].id" -o tsv`
          fi
          appClientId=`az ad sp list --display-name "${{env.USER_IDENTITY_NAME}}" --query "[?displayName=='${{env.USER_IDENTITY_NAME}}'].appId" --out tsv`
          echo "Certificate ID: '${certificateId}'"
          echo "Managed identity appClientId: ${appClientId}"
          
          deploymentOutput=`az deployment group create \
                                        --name "${{env.APP_NAME}}-app-deployment" \
                                        --resource-group ${{env.ACA_RESOURCE_GROUP}} \
                                        --template-file ./${{env.RELEASE_DIR_NAME}}/aca/workload.bicep \
                                        --parameters acaName="${{env.ACA_NAME}}" \
                                                     acaTags="${{vars.ACA_RESOURCE_TAGS}}" \
                                                     appVersion="${{env.VERSION}}" \
                                                     appName="${{env.APP_NAME}}" \
                                                     appClientId="${appClientId}" \
                                                     containerImage="${{env.CONTAINER_IMAGE}}" \
                                                     containerRegistryName="${{env.CONTAINER_REGISTRY_NAME}}" \
                                                     containerRegistrySubscriptionId="${{env.CONTAINER_REGISTRY_SUBSCRIPTION_ID}}" \
                                                     containerRegistryRG="${{env.CONTAINER_REGISTRY_RESOURCE_GROUP}}" \
                                                     certificateId="${certificateId}" \
                                                     dnsZoneName="${{secrets.DNS_ZONE_NAME}}" \
                                                     parentDnsZoneName="${{secrets.PARENT_DNS_ZONE_NAME}}" \
                                                     location="${{secrets.AZURE_LOCATION}}" `
          echo "Deployment output:"
          echo "=================="
          echo "$deploymentOutput"
          echo "=================="

          if [[ -z $certificateId ]]; then
            certificateId=`az containerapp env certificate list -g ${{env.ACA_RESOURCE_GROUP}} --name ${{env.ACA_NAME}} --query "[?properties.subjectName=='${{env.HOST_NAME}}'].id" -o tsv`
            if [[ ! -z $certificateId ]]; then
              echo "Binding certificate '${certificateId}' to hostname '${{env.HOST_NAME}}' using CLI, as doing this the first time ib Bicep deployment leads to a circular reference issue"
              az containerapp hostname bind -n "${{env.APP_NAME}}" -g "${{env.ACA_RESOURCE_GROUP}}" --hostname "${{env.HOST_NAME}}" --certificate "${certificateId}"
            else
              echo "No certificate found for '${{env.HOST_NAME}}'"
            fi
          else
            echo "This is not the first deployment, skipping the AZ CLI certificate binding. Certificate was either bound already or the binding happened in the Bicep deployment."
          fi
